name: PR

on:
  workflow_call:

jobs:
  app:
    name: app changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: running app
        run: echo "app changed ran"
