name: PR

on:
  pull_request:
  push:
    branches: master

jobs:
  changes:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      app: ${{ steps.filter.outputs.app }}
      test: ${{ steps.filter.outputs.test }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            app:
              - 'app/**'
            test:
              - 'test/**'

  app:
    needs:
      - changes
    if: ${{ github.ref == 'refs/heads/master' || needs.changes.outputs.app == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: running app
        run: echo "app changed ran"

  test:
    needs:
      - changes
    if: ${{ github.ref == 'refs/heads/master' || needs.changes.outputs.test == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: running test
        run: echo "test changed ran"
