name: PR

on:
  workflow_call:

jobs:
  test:
    name: test changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: running test
        # this should fail
        run: ./tmp.sh

